# Generated by Django 4.2.7 on 2023-12-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_body_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='global_post',
            field=models.BooleanField(default=False, verbose_name='Админский пост'),
        ),
    ]
