# Generated by Django 4.2.7 on 2023-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверочный код'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verificated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подтверждение аккаунта'),
        ),
    ]
