# Generated by Django 4.2.2 on 2023-12-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_generated_code',
            field=models.TimeField(blank=True, null=True, verbose_name='Последняя генерация кода'),
        ),
    ]
