# Generated by Django 4.2.2 on 2023-12-22 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_last_generated_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
