# Generated by Django 4.2.2 on 2023-12-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_message_updated_alter_message_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
    ]
